name = "FMISensitivity"
uuid = "3e748fe5-cd7f-4615-8419-3159287187d2"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "0.1.3"

[deps]
FMICore = "8af89139-c281-408e-bce2-3005eb87462f"
ForwardDiffChainRules = "c9556dd2-1aed-4cfe-8560-1557cf593001"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[compat]
FMICore = "0.19.3"
ForwardDiffChainRules = "0.2.0"
SciMLSensitivity = "6.51.2 - 7.51"
julia = "1.6"
